### ISSUE TITLE
issue with install-fabric.sh fabric

### ISSUE THREAD

**Issue by alvinapca** [piachristel/open-source-fabric-optee-chaincode#2]
Hi Christina, I was testing out your example and encountered an error, I hope to ask for some advice. I am using an Ubuntu 20.04. When I tried to execute sudo ./install-fabric.sh fabric, I encounter the following error below.

**Makefile:89: *** "No go in PATH: Check dependencies".  Stop.**

After going through line by line, the error was produced by this make line in the code.

git checkout release-1.4 || exit 1
git checkout v1.4.1
sudo chmod 666 /var/run/docker.sock || exit 1
**make** 

I executed each section of install-fabric.sh in the terminal as the following
**sudo ./install-fabric.sh cMake
./install-fabric.sh go
sudo  ./install-fabric.sh remaining_prerequisites
sudo ./install-fabric.sh fabric**

I tested various solutions recommended for this error but was still unable to resolve it. May I please ask if you have encountered this error in the OS you were using and how did you resolve it?

**Comment by taehjoon** [comment]
Hi
In my case, I just add symbolic link in bin directory.
maybe in '/bin' or '/usr/bin'

then,
> Makefile:89: *** "No go in PATH: Check dependencies". Stop.
>

error can fixed

**Comment by alvinapca** [comment]
Hi, I am still new to this, may i know more please?

I went through how to create a symbolic link on ubuntu
https://linuxhint.com/create_symbolic_link_ubuntu/

I am not sure if I got the source directory and link file directory correct. I tried the following commands but none of them fix the error.

sudo ln -s  /usr/local/go /bin
sudo ln -s  /usr/local/go /usr/bin

sudo ln -s  /usr/local/go/bin /bin
sudo ln -s  /usr/local/go/bin /usr/bin

sudo ln -s  /usr/local/go/bin/go /bin
sudo ln -s  /usr/local/go/bin/go /usr/bin

sudo ln -s  /usr/local/go/bin/go /bin/go
sudo ln -s  /usr/local/go/bin/go /usr/bin/go

**Comment by taehjoon** [comment]
`ln -s /usr/local/go/bin/go /usr/bin/go`
I use this command.....
Could you like to check the path of Go? using 'go env'
or please show your .profile settings
I add Go path like this,

> export GOROOT=/usr/local/go
> export GOPATH=$HOME/go:$HOME/
> export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin

**Comment by taehjoon** [comment]
> `ln -s /usr/local/go/bin/go /usr/bin/go`
> I use this command.....
> Could you like to check the path of Go? using 'go env'
> or please show your .profile settings
> I add Go path like this,
> 
> > export GOROOT=/usr/local/go
> > export GOPATH=$HOME/go:$HOME/
> > export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin

**Comment by alvinapca** [comment]
Hi, thank you very much for your reply.

Attached are the outputs after i run "sudo ln -s /usr/local/go/bin/go /usr/bin/go"
[install fabric error.pdf](https://github.com/piachristel/open-source-fabric-optee-chaincode/files/6747322/install.fabric.error.pdf)


After running "sudo ln -s /usr/local/go/bin/go /usr/bin/go", the error **Makefile:89: *** "No go in PATH: Check dependencies". Stop.** is resolved although a new list of errors with the last line being a warning appeared as shown in the last part of the attachment.

I hope to ask please if there is any way to check at this stage if the fabric has been installed properly?

**Comment by taehjoon** [comment]
Unfortunately I also encounter same problem
but I think that every file is installed we need.

I recommend you execute 
> chaincode-wrapper.md

and In this sequence, solve encountered problem.
If you need, install 
https://github.com/golang/tools

Sorry for not providing a perfect solution about it.
Good luck

**Comment by alvinapca** [comment]
Thank you! Last thing I hope to ask. I really learnt something about symbolic link after struggling on this for 2 days. If you have a paypal account, may I ask if I may have it (can be a private channel) to transfer you an amount to buy you a meal/drink to show my appreciation?

**Comment by taehjoon** [comment]
I appreciate the offer, but I haven't provided enough information to be appreciated.
I am currently a college student who is interested in this project.
So, If you also studying this project, I hope we can help each other. : )

**Comment by alvinapca** [comment]
Yes, I am studying this project in hopes to continue/expand it! May I ask if there is a preferred way of communication(email, telegram etc) you like to use to keep in touch as I don't use this often and I do not have alerts when a new message has popped up?

**Comment by taehjoon** [comment]
@alvinapca 
If you contact me, send my email zxc8283@daum.net

But I'm not sure whether it will be of any help to you.
and I will remove this message for my private. 
thank you

**Comment by alvinapca** [comment]
Ok Done, thanks again
